#!/bin/sh

# Disable in CI
[ -n "$CI" ] && exit 0

. "$(dirname "$0")/_/husky.sh"


if [ "$OSTYPE" = "linux-gnu" ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

npm run pre-commit
