-- CreateEnum
CREATE TYPE "StudyProgress" AS ENUM ('START_01', 'DATA_PROCESSING_02', 'QUESTIONS_03', 'INTRO_STUDY_04', 'INTRO_BIAS_05', 'ATTENTION_CHECK_06', 'INTRO_TASK_07', 'ARTICLES_08', 'TRUST_CHECK_09', 'END_10');

-- AlterTable
ALTER TABLE "Participant" ADD COLUMN     "articleProgress" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "studyProgress" "StudyProgress" NOT NULL DEFAULT E'START_01';
